version: 2
updates:
  # Maintain dependencies for container images
  - package-ecosystem: "docker"
    # blocked due to: https://github.com/dependabot/dependabot-core/issues/2178
    directory: "/vaultwarden"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    # blocked due to: https://github.com/dependabot/dependabot-core/issues/2178
    directory: "/monito-rss"
    schedule:
      interval: "daily"
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
