version: 2
updates:
  # Maintain dependencies for container images
  - package-ecosystem: "docker"
    # blocked due to: https://github.com/dependabot/dependabot-core/issues/2178
    directory: "/bitwarden_rs"
    schedule:
      interval: "daily"
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  # Maintain dependencies for Go projects
  - package-ecosystem: "gomod"
    directory: "/hydroxide"
    schedule:
      interval: "daily"

